### PR TITLE
made Appbar on the Homepage

### PR DESCRIPTION
**Pull request by brainless-coder**
I have made the AppBar. Attaching a screenshot of the final outcome, let me know if some changes are needed.

Screenshot_1639945471

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
It looks really good. Can you make a few more changes:

1. Increase the size of the Pokeball icon
2. Decrease the size of the Pokemon text image
3. Increase the size of the search icon
4. Change the background color of the app bar to white
5. change the elevation of the app bar to 0
6. And increase the height of the app bar so that there is sufficient padding above the pokemon image

**Comment by infiniteoverflow** [comment]
And also mention the issue number you are working on. This is a recommended practise when you are working on a PR

**Comment by brainless-coder** [comment]
done with all the above mentioned changes for AppBar #6 
Attaching a screenshot for your reference.
Screenshot_1640366188

**Comment by infiniteoverflow** [comment]
Looks amazing @brainless-coder .

**Pull request merged**
